service: msacwatchschedule

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  api:
    handler: server.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
