service: msacwatchschedule

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  api:
    handler: handler
    events:
      - http: ANY /
      - http: "ANY /{proxy+}"

plugins:
  - serverless-dynamodb-local
  - serverless-offline # serverless-offline needs to be last in the list

custom:
  serverless-offline:
    httpPort: 5000
    noPrependStageInUrl: true
  dynamodb:
    stages:
      - ${self:provider.stage}

useDotenv: true
